# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='group',
        ),
        migrations.AddField(
            model_name='quote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes_made', to='login_app.User'),
        ),
        migrations.AddField(
            model_name='quote',
            name='quotelist',
            field=models.ManyToManyField(related_name='quotelist', to='login_app.User'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='message',
            field=models.CharField(max_length=700),
        ),
    ]
